### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by SiyuanYan1** [mertyg/debug-mistakes-cce#1]
Excellent work! Can I know when you will release the code?

**Comment by mertyg** [comment]
Thank you for your interest & kind words @redlessme ! We're actively working on it, should be released latest by the start of ICML (<2 weeks)

**Comment by yu1206** [comment]
expectance

**Comment by mertyg** [comment]
Hello @redlessme , @yu1206 we just released the code and I'm closing this issue now. Let me know if you need anything else!
